service: node-crud2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: 'us-east-2'
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-2:512345104267:table/MoviesTable

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  createMovie:
    handler: src/addMovie.addMovie
    events:
      - httpApi:
          path: /movies
          method: post

resources:
  Resources:
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MoviesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
