service: node-crud2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: 'us-east-2'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-2:512345104267:table/MoviesTable

plugins:
  - serverless-plugin-typescript

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  createMovie:
    handler: src/addMovie.addMovie
    events:
      - httpApi:
          path: /movies
          method: post
  getMovies:
    handler: src/getMovies.getMovies
    events:
      - httpApi:
          path: /movies
          method: get
  getFilms:
    handler: src/swGetFilms.getFilms
    events:
      - httpApi:
          path: /peliculas
          method: get
  getCharacters:
    handler: src/swGetCharacters.getCharacters
    events:
      - httpApi:
          path: /personajes
          method: get
  getSpecies:
    handler: src/swGetSpecies.getSpecies
    events:
      - httpApi:
          path: /especies
          method: get
  getMovie:
    handler: src/getMovie.getMovie
    events:
      - httpApi:
          path: /movies/{id}
          method: get
  updateMovie:
    handler: src/updateMovie.updateMovie
    events:
      - httpApi:
          path: /movies/{id}
          method: put
  deleteMovie:
    handler: src/deleteMovie.deleteMovie
    events:
      - httpApi:
          path: /movies/{id}
          method: delete

resources:
  Resources:
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MoviesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
